import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  camera: {
    flex: 1,
    width: '100%',
  },
  recordButtonContainer: {
    alignItems: 'center',
    position: 'absolute',
    bottom: '15%',
    left: '50%',
    transform: [{ translateX: -40 }],
  },
  recordButton: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 2,
    borderColor: 'black',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  timerContainer: {
    position: 'absolute',
    top: '5%',
    left: '50%',
    transform: [{ translateX: -40 }],
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'red',
  },
  timerText: {
    fontSize: 18,
    color: 'white',
  },
  permissionButton: {
    backgroundColor: '#581DB9',
    padding: 10,
    borderRadius: 10,
    margin: 10,
    position: 'absolute',
  },
  infoContainer: {
    position: 'absolute',
    top: '10%',
    left: 5,
    padding: 15,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    borderRadius: 5,
    width: 210,
    height: 150,
    justifyContent: 'center',
  },
  infoText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: 'white',
  },
  modalContainer: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
    height: '90%',
    justifyContent: 'center',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 10,
  },
  modalSubtitle: {
    fontSize: 15,
    textAlign: 'center',
    color: 'gray',
    marginBottom: 20,
  },
  modalLabel: {
    fontSize: 16,
    color: 'black',
    marginTop: 20,
    fontWeight: 'bold',
    marginHorizontal: 10,
  },

  button: {
    marginVertical: 10,
    paddingVertical: 12,
    backgroundColor: '#581DB9',
    borderRadius: 10,
    alignItems: 'center',
    alignSelf: 'center',
    width: '50%',
  },
  descriptionInput: {
    marginVertical: 10,
    backgroundColor: 'white',
    height: 60,
    borderRadius: 10,
    paddingHorizontal: 10,
  },
  progressContainer: {
    width: '100%',
    backgroundColor: 'white',
    padding: 10,
    borderRadius: 10,
    bottom: 90,
  },
  progressText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#581DB9',
    marginBottom: 10,
    alignSelf: 'center',
  },
  progress: {
    width: '100%',
    height: 10,
    backgroundColor: 'gray',
    borderRadius: 10,
  },
});
